# Generated by Django 5.2.2 on 2026-04-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(db_column='IDOrder', primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField(db_column='TotalAmount', default=0)),
                ('order_date', models.DateTimeField(auto_now_add=True, db_column='OrderDate')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Declined'), (3, 'Shipped'), (4, 'In Transit'), (5, 'Delivered')], db_column='Status', default=0)),
                ('delivery_address', models.CharField(blank=True, db_column='DeliveryAddress', max_length=255)),
                ('pickup_address', models.CharField(blank=True, db_column='PickupAddress', max_length=255)),
            ],
            options={
                'db_table': 'Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(db_column='IDOrderItem', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('price', models.IntegerField(db_column='Price')),
                ('total_items_price', models.IntegerField(db_column='TotalItemsPrice')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(db_column='IDPayment', primary_key=True, serialize=False)),
                ('amount', models.IntegerField(db_column='Amount')),
                ('payment_method', models.CharField(db_column='PaymentMethod', max_length=100)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, db_column='TransactionDate')),
            ],
            options={
                'db_table': 'Payments',
            },
        ),
    ]
