# Generated by Django 5.2.2 on 2026-04-01 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(db_column='IDBuyer', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.buyer'),
        ),
        migrations.AddField(
            model_name='order',
            name='farmer',
            field=models.ForeignKey(db_column='IDFarmer', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.farmer'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(db_column='IDOrder', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_list',
            field=models.ForeignKey(db_column='IDProductList', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productlist'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(db_column='IDOrder', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
    ]
