# Generated by Django 5.2.2 on 2026-04-07 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_commune',
            field=models.ForeignKey(blank=True, db_column='DeliveryCommune', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to='locations.commune'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_wilaya',
            field=models.ForeignKey(blank=True, db_column='DeliveryWilaya', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to='locations.wilaya'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_commune',
            field=models.ForeignKey(blank=True, db_column='PickupCommune', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_orders', to='locations.commune'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_wilaya',
            field=models.ForeignKey(blank=True, db_column='PickupWilaya', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_orders', to='locations.wilaya'),
        ),
    ]
