# Generated by Django 5.2.2 on 2026-04-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReview',
            fields=[
                ('id', models.AutoField(db_column='IDItemReview', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(db_column='Rating')),
                ('review_text', models.CharField(blank=True, db_column='ReviewText', max_length=255)),
                ('review_date', models.DateTimeField(auto_now_add=True, db_column='ReviewDate')),
            ],
            options={
                'db_table': 'ItemReview',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(db_column='IDShipping', primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(blank=True, db_column='TrackingNumber', max_length=100)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Declined'), (3, 'Picked Up'), (4, 'In Transit'), (5, 'Delivered')], db_column='Status', default=0)),
                ('shipping_fee', models.IntegerField(db_column='ShippingFee', default=0)),
                ('pickup_date', models.DateTimeField(blank=True, db_column='PickupDate', null=True)),
                ('estimated_delivery_date', models.DateTimeField(blank=True, db_column='EstimatedDeliveryDate', null=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, db_column='ActualDeliveryDate', null=True)),
            ],
            options={
                'db_table': 'Shipment',
                'ordering': ['-pickup_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransporterReview',
            fields=[
                ('id', models.AutoField(db_column='IDReview', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(db_column='Rating')),
                ('review_text', models.CharField(blank=True, db_column='ReviewText', max_length=255)),
                ('review_date', models.DateTimeField(auto_now_add=True, db_column='ReviewDate')),
            ],
            options={
                'db_table': 'TransporterReview',
            },
        ),
    ]
