# Generated by Django 5.2.2 on 2026-04-01 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreview',
            name='order_item',
            field=models.ForeignKey(db_column='IDOrderItem', on_delete=django.db.models.deletion.CASCADE, related_name='item_reviews', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(db_column='IDOrder', on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order'),
        ),
    ]
