# Generated by Django 5.2.2 on 2026-04-01 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='transporter',
            field=models.ForeignKey(blank=True, db_column='IDTransporter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='users.transporter'),
        ),
        migrations.AddField(
            model_name='transporterreview',
            name='buyer',
            field=models.ForeignKey(db_column='IDBuyer', on_delete=django.db.models.deletion.CASCADE, related_name='transporter_reviews', to='users.buyer'),
        ),
        migrations.AddField(
            model_name='transporterreview',
            name='shipment',
            field=models.ForeignKey(db_column='IDShipping', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='logistics.shipment'),
        ),
    ]
