# Generated by Django 5.2.2 on 2026-04-07 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='IDWilaya', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='Code', max_length=2, unique=True)),
                ('name', models.CharField(db_column='Name', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Wilaya',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.PositiveIntegerField(db_column='IDCommune', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=120)),
                ('wilaya', models.ForeignKey(db_column='IDWilaya', on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='locations.wilaya')),
            ],
            options={
                'db_table': 'Commune',
                'ordering': ['wilaya_id', 'name'],
                'constraints': [models.UniqueConstraint(fields=('wilaya', 'name'), name='unique_commune_name_per_wilaya')],
            },
        ),
    ]
