# Generated by Django 5.2.2 on 2026-04-01 18:12

import apps.users.models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(db_column='IDPerson', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_column='FirstName', max_length=100)),
                ('last_name', models.CharField(blank=True, db_column='LastName', max_length=100)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255)),
                ('phone_number', models.CharField(blank=True, db_column='PhoneNumber', max_length=30)),
                ('personal_picture_url', models.CharField(blank=True, db_column='personalPictureURL', max_length=255)),
                ('documents_url', models.CharField(blank=True, db_column='DocumentsURL', max_length=255)),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('username', models.CharField(db_column='Username', max_length=100, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending Approval'), (1, 'Approved'), (2, 'Rejected')], db_column='Status', db_index=True, default=0)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Farmer'), (2, 'Buyer'), (3, 'Transporter'), (4, 'Ministry')], db_column='Role', db_index=True, default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'db_table': 'Person',
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.AutoField(db_column='IDAdmin', primary_key=True, serialize=False)),
                ('total_processes', models.IntegerField(db_column='TotalProcesses', default=0)),
                ('region_code', models.IntegerField(blank=True, db_column='RegionCode', null=True)),
                ('person', models.OneToOneField(db_column='IDPerson', on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(db_column='IDBuyer', primary_key=True, serialize=False)),
                ('person', models.OneToOneField(db_column='IDPerson', on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Buyer',
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(db_column='IDFarmer', primary_key=True, serialize=False)),
                ('average_rating', models.IntegerField(blank=True, db_column='AverageRating', null=True)),
                ('total_reviews', models.IntegerField(blank=True, db_column='TotalReviews', null=True)),
                ('person', models.OneToOneField(db_column='IDPerson', on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Farmer',
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.AutoField(db_column='IDRequest', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_column='FirstName', max_length=100)),
                ('last_name', models.CharField(blank=True, db_column='LastName', max_length=100)),
                ('email', models.EmailField(db_column='Email', max_length=150)),
                ('phone_number', models.CharField(blank=True, db_column='PhoneNumber', max_length=30)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255)),
                ('requested_role', models.PositiveSmallIntegerField(db_column='RequestedRole')),
                ('personal_picture_url', models.CharField(blank=True, db_column='personalPictureURL', max_length=255)),
                ('documents_url', models.CharField(blank=True, db_column='DocumentsURL', max_length=255)),
                ('request_date', models.DateTimeField(auto_now_add=True, db_column='RequestDate')),
                ('review_date', models.DateTimeField(blank=True, db_column='ReviewDate', null=True)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], db_column='Status', db_index=True, default=0)),
                ('admin', models.ForeignKey(blank=True, db_column='IDAdmin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests', to='users.adminprofile')),
            ],
            options={
                'db_table': 'JoinRequest',
            },
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.AutoField(db_column='IDTransporter', primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(blank=True, db_column='Capacity', null=True)),
                ('service_area', models.CharField(blank=True, db_column='ServiceArea', max_length=255)),
                ('vehicle_type', models.CharField(blank=True, db_column='VehicleType', max_length=100)),
                ('average_rating', models.IntegerField(blank=True, db_column='AverageRating', null=True)),
                ('total_reviews', models.IntegerField(blank=True, db_column='TotalReviews', null=True)),
                ('person', models.OneToOneField(db_column='IDPerson', on_delete=django.db.models.deletion.CASCADE, related_name='transporter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Transporter',
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(db_column='IDFarm', primary_key=True, serialize=False)),
                ('location', models.CharField(db_column='Location', max_length=255)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=150)),
                ('area', models.IntegerField(blank=True, db_column='Area', null=True)),
                ('farmer', models.ForeignKey(db_column='IDFarmer', on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='users.farmer')),
            ],
            options={
                'db_table': 'Farm',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('location'), name='unique_farm_location_ci')],
            },
        ),
    ]
