# Generated by Django 5.2.2 on 2026-04-07 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='commune',
            field=models.ForeignKey(blank=True, db_column='IDCommune', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyers', to='locations.commune'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='wilaya',
            field=models.ForeignKey(blank=True, db_column='IDWilaya', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyers', to='locations.wilaya'),
        ),
        migrations.AddField(
            model_name='farm',
            name='commune',
            field=models.ForeignKey(blank=True, db_column='IDCommune', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farms', to='locations.commune'),
        ),
        migrations.AddField(
            model_name='farm',
            name='wilaya',
            field=models.ForeignKey(blank=True, db_column='IDWilaya', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farms', to='locations.wilaya'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='delivery_wilayas',
            field=models.ManyToManyField(blank=True, db_table='TransporterDeliveryWilaya', related_name='transporters', to='locations.wilaya'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='max_load_kg',
            field=models.PositiveIntegerField(blank=True, db_column='MaxLoadKg', null=True),
        ),
    ]
