# Generated by Codex on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["status"], name="report_status_idx"),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["created_at"], name="report_created_idx"),
        ),
    ]
