# Generated by Django 5.2.2 on 2026-04-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='IDCategory', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'Category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfficialPrice',
            fields=[
                ('id', models.AutoField(db_column='IDOfficialPrice', primary_key=True, serialize=False)),
                ('max_price', models.IntegerField(db_column='MaxPrice')),
            ],
            options={
                'db_table': 'OfficialPrice',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='IDProduct', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'Product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(db_column='IDProductList', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='Quantity', default=0)),
                ('price', models.IntegerField(db_column='Price', default=0)),
            ],
            options={
                'db_table': 'ProductList',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(db_column='IDSeason', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'Season',
                'ordering': ['name'],
            },
        ),
    ]
