# Generated by Django 5.2.2 on 2026-04-01 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialprice',
            name='admin',
            field=models.ForeignKey(db_column='IDAdmin', on_delete=django.db.models.deletion.PROTECT, related_name='official_prices', to='users.adminprofile'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(db_column='IDCategory', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='officialprice',
            name='product',
            field=models.ForeignKey(db_column='IDProduct', on_delete=django.db.models.deletion.PROTECT, related_name='official_prices', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productlist',
            name='farmer',
            field=models.ForeignKey(db_column='IDFarmer', on_delete=django.db.models.deletion.CASCADE, related_name='product_listings', to='users.farmer'),
        ),
        migrations.AddField(
            model_name='productlist',
            name='product',
            field=models.ForeignKey(db_column='IDProduct', on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='officialprice',
            name='season',
            field=models.ForeignKey(db_column='IDSeason', on_delete=django.db.models.deletion.PROTECT, related_name='official_prices', to='catalog.season'),
        ),
    ]
