# Generated by Django 5.2.2 on 2026-04-02

from django.db import migrations, models


CATALOG = [
    ("Vegetables", "Tomato", 60, 180),
    ("Vegetables", "Cherry Tomato", 150, 300),
    ("Vegetables", "Potato", 50, 150),
    ("Vegetables", "Sweet Potato", 120, 300),
    ("Vegetables", "Onion", 60, 140),
    ("Vegetables", "Garlic", 400, 900),
    ("Vegetables", "Carrot", 60, 120),
    ("Vegetables", "Zucchini", 80, 200),
    ("Vegetables", "Eggplant", 80, 200),
    ("Vegetables", "Bell Pepper", 120, 300),
    ("Vegetables", "Chili Pepper", 150, 400),
    ("Vegetables", "Lettuce", 120, 200),
    ("Vegetables", "Cabbage", 80, 150),
    ("Vegetables", "Cauliflower", 100, 250),
    ("Vegetables", "Broccoli", 200, 400),
    ("Vegetables", "Turnip", 60, 120),
    ("Vegetables", "Beetroot", 80, 180),
    ("Vegetables", "Pumpkin", 70, 150),
    ("Vegetables", "Squash", 80, 200),
    ("Vegetables", "Cucumber", 80, 180),
    ("Vegetables", "Green Beans", 200, 500),
    ("Vegetables", "Peas", 200, 500),
    ("Vegetables", "Spinach", 150, 300),
    ("Vegetables", "Parsley", 50, 120),
    ("Vegetables", "Coriander", 50, 120),
    ("Vegetables", "Celery", 100, 200),
    ("Vegetables", "Leek", 120, 250),
    ("Vegetables", "Artichoke", 200, 400),
    ("Vegetables", "Fennel", 120, 250),
    ("Vegetables", "Okra", 200, 500),
    ("Vegetables", "Radish", 60, 120),
    ("Vegetables", "Swiss Chard", 100, 200),
    ("Vegetables", "Arugula", 100, 200),
    ("Vegetables", "Endive", 120, 250),
    ("Vegetables", "Watercress", 100, 200),
    ("Vegetables", "Kale", 150, 300),
    ("Vegetables", "Mustard Greens", 120, 250),
    ("Fruits", "Apple", 250, 600),
    ("Fruits", "Banana", 250, 450),
    ("Fruits", "Orange", 120, 300),
    ("Fruits", "Blood Orange", 150, 350),
    ("Fruits", "Lemon", 200, 400),
    ("Fruits", "Clementine", 150, 350),
    ("Fruits", "Mandarin", 150, 350),
    ("Fruits", "Strawberry", 300, 800),
    ("Fruits", "Raspberry", 800, 1500),
    ("Fruits", "Blackberry", 800, 1500),
    ("Fruits", "Blueberry", 1000, 2000),
    ("Fruits", "Watermelon", 60, 150),
    ("Fruits", "Melon", 100, 250),
    ("Fruits", "Grapes", 200, 500),
    ("Fruits", "Pomegranate", 200, 500),
    ("Fruits", "Fig", 200, 600),
    ("Fruits", "Dates (Deglet Nour)", 300, 1200),
    ("Fruits", "Dates (Ghars)", 200, 800),
    ("Fruits", "Peach", 200, 500),
    ("Fruits", "Nectarine", 250, 600),
    ("Fruits", "Apricot", 200, 500),
    ("Fruits", "Plum", 200, 500),
    ("Fruits", "Cherry", 500, 1200),
    ("Fruits", "Pear", 200, 500),
    ("Fruits", "Kiwi", 400, 800),
    ("Fruits", "Mango", 500, 1200),
    ("Fruits", "Pineapple", 400, 900),
    ("Fruits", "Avocado", 400, 800),
    ("Fruits", "Guava", 300, 700),
    ("Fruits", "Papaya", 400, 900),
    ("Fruits", "Coconut", 300, 700),
    ("Fruits", "Persimmon", 200, 500),
    ("Fruits", "Mulberry", 200, 600),
    ("Fruits", "Prickly Pear (Figue de Barbarie)", 100, 300),
    ("Herbs", "Mint", 80, 200),
    ("Herbs", "Basil", 100, 250),
    ("Herbs", "Thyme", 150, 300),
    ("Herbs", "Rosemary", 150, 300),
    ("Herbs", "Sage", 150, 300),
    ("Herbs", "Dill", 100, 250),
    ("Dry Products", "Almond", 1200, 2500),
    ("Dry Products", "Peanut", 300, 600),
    ("Dry Products", "Walnut", 1200, 2500),
    ("Dry Products", "Pistachio", 2000, 3500),
]


def seed_controlled_catalog(apps, _schema_editor):
    Category = apps.get_model("catalog", "Category")
    Product = apps.get_model("catalog", "Product")
    ProductList = apps.get_model("catalog", "ProductList")
    OfficialPrice = apps.get_model("catalog", "OfficialPrice")

    category_cache = {}
    allowed_names = set()

    for category_name, name, min_price, max_price in CATALOG:
        category = category_cache.get(category_name)
        if category is None:
            category, _ = Category.objects.get_or_create(name=category_name)
            category_cache[category_name] = category

        Product.objects.update_or_create(
            name=name,
            defaults={
                "category": category,
                "unit": "kg",
                "min_price": min_price,
                "max_price": max_price,
            },
        )
        allowed_names.add(name)

    disallowed_products = Product.objects.exclude(name__in=allowed_names)
    ProductList.objects.filter(product__in=disallowed_products).delete()
    OfficialPrice.objects.filter(product__in=disallowed_products).delete()
    disallowed_products.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="max_price",
            field=models.IntegerField(db_column="MaxPrice", default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="min_price",
            field=models.IntegerField(db_column="MinPrice", default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(db_column="Unit", default="kg", max_length=20),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_column="Name", max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name="productlist",
            constraint=models.UniqueConstraint(fields=("farmer", "product"), name="unique_farmer_product_listing"),
        ),
        migrations.RunPython(seed_controlled_catalog, migrations.RunPython.noop),
    ]
