# Generated by Django 5.2.2 on 2026-04-02

from django.db import migrations, models

from apps.catalog.catalog_data import load_controlled_catalog


def seed_controlled_catalog(apps, _schema_editor):
    Category = apps.get_model("catalog", "Category")
    Product = apps.get_model("catalog", "Product")

    allowed_names = set()
    category_cache = {}

    for item in load_controlled_catalog():
        category_name = item["category"]
        category = category_cache.get(category_name)
        if category is None:
            category, _ = Category.objects.get_or_create(name=category_name)
            category_cache[category_name] = category

        Product.objects.update_or_create(
            name=item["name"],
            defaults={
                "category": category,
                "unit": item["unit"],
                "min_price": item["min_price_dzd"],
                "max_price": item["max_price_dzd"],
                "is_active": item["is_active"],
            },
        )
        allowed_names.add(item["name"])

    Product.objects.exclude(name__in=allowed_names).update(is_active=False)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_controlled_market_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(db_column="IsActive", default=True),
        ),
        migrations.RunPython(seed_controlled_catalog, migrations.RunPython.noop),
    ]
