-- PostgreSQL-ready schema for the target database design.
-- Preserves exact table and column names by using quoted identifiers.

BEGIN;

CREATE TABLE IF NOT EXISTS "Person" (
    "IDPerson" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FirstName" VARCHAR(100),
    "LastName" VARCHAR(100),
    "Address" VARCHAR(255),
    "PhoneNumber" VARCHAR(30),
    "personalPictureURL" VARCHAR(255),
    "DocumentsURL" VARCHAR(255),
    "Email" VARCHAR(150) UNIQUE,
    "Username" VARCHAR(100) UNIQUE,
    "Password" VARCHAR(255),
    "Status" INTEGER,
    "Role" INTEGER
);

CREATE TABLE IF NOT EXISTS "Farmer" (
    "IDFarmer" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IDPerson" INTEGER UNIQUE,
    "AverageRating" INTEGER,
    "TotalReviews" INTEGER,
    CONSTRAINT "FK_Farmer_Person" FOREIGN KEY ("IDPerson") REFERENCES "Person" ("IDPerson")
);

CREATE TABLE IF NOT EXISTS "Buyer" (
    "IDBuyer" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IDPerson" INTEGER UNIQUE,
    CONSTRAINT "FK_Buyer_Person" FOREIGN KEY ("IDPerson") REFERENCES "Person" ("IDPerson")
);

CREATE TABLE IF NOT EXISTS "Admin" (
    "IDAdmin" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IDPerson" INTEGER UNIQUE,
    "TotalProcesses" INTEGER,
    "RegionCode" INTEGER,
    CONSTRAINT "FK_Admin_Person" FOREIGN KEY ("IDPerson") REFERENCES "Person" ("IDPerson")
);

CREATE TABLE IF NOT EXISTS "Transporter" (
    "IDTransporter" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IDPerson" INTEGER UNIQUE,
    "Capacity" INTEGER,
    "ServiceArea" VARCHAR(255),
    "VehicleType" VARCHAR(100),
    "AverageRating" INTEGER,
    "TotalReviews" INTEGER,
    CONSTRAINT "FK_Transporter_Person" FOREIGN KEY ("IDPerson") REFERENCES "Person" ("IDPerson")
);

CREATE TABLE IF NOT EXISTS "Farm" (
    "IDFarm" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IDFarmer" INTEGER,
    "Location" VARCHAR(255) UNIQUE,
    "Name" VARCHAR(150),
    "Area" INTEGER,
    CONSTRAINT "FK_Farm_Farmer" FOREIGN KEY ("IDFarmer") REFERENCES "Farmer" ("IDFarmer")
);

CREATE TABLE IF NOT EXISTS "Category" (
    "IDCategory" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS "Product" (
    "IDProduct" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(100) UNIQUE,
    "IDCategory" INTEGER,
    "Unit" VARCHAR(20),
    "MinPrice" INTEGER,
    "MaxPrice" INTEGER,
    CONSTRAINT "FK_Product_Category" FOREIGN KEY ("IDCategory") REFERENCES "Category" ("IDCategory")
);

CREATE TABLE IF NOT EXISTS "Season" (
    "IDSeason" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS "OfficialPrice" (
    "IDOfficialPrice" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MaxPrice" INTEGER,
    "IDSeason" INTEGER,
    "IDProduct" INTEGER,
    "IDAdmin" INTEGER,
    CONSTRAINT "FK_OfficialPrice_Season" FOREIGN KEY ("IDSeason") REFERENCES "Season" ("IDSeason"),
    CONSTRAINT "FK_OfficialPrice_Product" FOREIGN KEY ("IDProduct") REFERENCES "Product" ("IDProduct"),
    CONSTRAINT "FK_OfficialPrice_Admin" FOREIGN KEY ("IDAdmin") REFERENCES "Admin" ("IDAdmin")
);

CREATE TABLE IF NOT EXISTS "ProductList" (
    "IDProductList" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IDProduct" INTEGER,
    "IDFarmer" INTEGER,
    "Quantity" INTEGER,
    "Price" INTEGER,
    CONSTRAINT "UQ_ProductList_Farmer_Product" UNIQUE ("IDFarmer", "IDProduct"),
    CONSTRAINT "FK_ProductList_Product" FOREIGN KEY ("IDProduct") REFERENCES "Product" ("IDProduct"),
    CONSTRAINT "FK_ProductList_Farmer" FOREIGN KEY ("IDFarmer") REFERENCES "Farmer" ("IDFarmer")
);

CREATE TABLE IF NOT EXISTS "Orders" (
    "IDOrder" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IDBuyer" INTEGER,
    "IDFarmer" INTEGER,
    "TotalAmount" INTEGER,
    "OrderDate" TIMESTAMPTZ,
    "Status" INTEGER,
    "DeliveryAddress" VARCHAR(255),
    "PickupAddress" VARCHAR(255),
    CONSTRAINT "FK_Orders_Buyer" FOREIGN KEY ("IDBuyer") REFERENCES "Buyer" ("IDBuyer"),
    CONSTRAINT "FK_Orders_Farmer" FOREIGN KEY ("IDFarmer") REFERENCES "Farmer" ("IDFarmer")
);

CREATE TABLE IF NOT EXISTS "OrderItem" (
    "IDOrderItem" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IDOrder" INTEGER,
    "IDProductList" INTEGER,
    "Quantity" INTEGER,
    "Price" INTEGER,
    "TotalItemsPrice" INTEGER,
    CONSTRAINT "FK_OrderItem_Orders" FOREIGN KEY ("IDOrder") REFERENCES "Orders" ("IDOrder"),
    CONSTRAINT "FK_OrderItem_ProductList" FOREIGN KEY ("IDProductList") REFERENCES "ProductList" ("IDProductList")
);

CREATE TABLE IF NOT EXISTS "Payments" (
    "IDPayment" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IDOrder" INTEGER,
    "Amount" INTEGER,
    "PaymentMethod" VARCHAR(100),
    "TransactionDate" TIMESTAMPTZ,
    CONSTRAINT "FK_Payments_Orders" FOREIGN KEY ("IDOrder") REFERENCES "Orders" ("IDOrder")
);

CREATE TABLE IF NOT EXISTS "Shipment" (
    "IDShipping" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IDOrder" INTEGER,
    "IDTransporter" INTEGER,
    "TrackingNumber" VARCHAR(100),
    "Status" INTEGER,
    "ShippingFee" INTEGER,
    "PickupDate" TIMESTAMPTZ,
    "EstimatedDeliveryDate" TIMESTAMPTZ,
    "ActualDeliveryDate" TIMESTAMPTZ,
    CONSTRAINT "FK_Shipment_Orders" FOREIGN KEY ("IDOrder") REFERENCES "Orders" ("IDOrder"),
    CONSTRAINT "FK_Shipment_Transporter" FOREIGN KEY ("IDTransporter") REFERENCES "Transporter" ("IDTransporter")
);

CREATE TABLE IF NOT EXISTS "TransporterReview" (
    "IDReview" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IDBuyer" INTEGER,
    "IDShipping" INTEGER,
    "Rating" INTEGER,
    "ReviewText" VARCHAR(255),
    "ReviewDate" TIMESTAMPTZ,
    CONSTRAINT "FK_TransporterReview_Buyer" FOREIGN KEY ("IDBuyer") REFERENCES "Buyer" ("IDBuyer"),
    CONSTRAINT "FK_TransporterReview_Shipment" FOREIGN KEY ("IDShipping") REFERENCES "Shipment" ("IDShipping")
);

CREATE TABLE IF NOT EXISTS "ItemReview" (
    "IDItemReview" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IDOrderItem" INTEGER,
    "Rating" INTEGER,
    "ReviewText" VARCHAR(255),
    "ReviewDate" TIMESTAMPTZ,
    CONSTRAINT "FK_ItemReview_OrderItem" FOREIGN KEY ("IDOrderItem") REFERENCES "OrderItem" ("IDOrderItem")
);

CREATE TABLE IF NOT EXISTS "JoinRequest" (
    "IDRequest" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IDAdmin" INTEGER,
    "FirstName" VARCHAR(100),
    "LastName" VARCHAR(100),
    "Email" VARCHAR(150),
    "PhoneNumber" VARCHAR(30),
    "Address" VARCHAR(255),
    "RequestedRole" INTEGER,
    "personalPictureURL" VARCHAR(255),
    "DocumentsURL" VARCHAR(255),
    "RequestDate" TIMESTAMPTZ,
    "ReviewDate" TIMESTAMPTZ,
    "Notes" VARCHAR(255),
    "Status" INTEGER,
    CONSTRAINT "FK_JoinRequest_Admin" FOREIGN KEY ("IDAdmin") REFERENCES "Admin" ("IDAdmin")
);

CREATE INDEX IF NOT EXISTS "IDX_Person_Role" ON "Person" ("Role");
CREATE INDEX IF NOT EXISTS "IDX_Person_Status" ON "Person" ("Status");
CREATE INDEX IF NOT EXISTS "IDX_Orders_Buyer" ON "Orders" ("IDBuyer");
CREATE INDEX IF NOT EXISTS "IDX_Orders_Farmer" ON "Orders" ("IDFarmer");
CREATE INDEX IF NOT EXISTS "IDX_Shipment_Order" ON "Shipment" ("IDOrder");
CREATE INDEX IF NOT EXISTS "IDX_ProductList_Farmer" ON "ProductList" ("IDFarmer");

COMMIT;
